### PR TITLE
Update pluggy dependency for conda 26.3.1 compatibility

### PR DESCRIPTION
**Pull request by jezdez**
conda 26.3.x broke with older versions of pluggy, regression introduced in https://github.com/conda/conda/pull/15840 and not caught in tests.

See https://github.com/conda/conda/pull/15953 for long-term fix. Feedstock update following.

### CODE REVIEW

File: main.py [hunk 1]
```diff
@@ -1601,6 +1601,15 @@ def patch_record_in_place(fn, record, subdir):
             if not dep.startswith("conda-anaconda-tos ")
         ] + ["conda-anaconda-tos >=0.2.1"]
 
+    # conda 26.3.1 started using pluggy.HookImpl.wrapper (added in pluggy 1.5.0)
+    # without bumping the recipe's `pluggy >=1.0.0` lower bound, causing
+    # AttributeError: 'HookImpl' object has no attribute 'wrapper' on every
+    # invocation when an older pluggy is installed.
+    # https://github.com/conda/conda/issues/15862
+    # https://github.com/conda/conda/issues/15985
+    if name == "conda" and VersionOrder(version) >= VersionOrder("26.3.1"):
```
Comment (jezdez) [inline main.py:1610]: Given https://github.com/conda/conda/pull/15953, we won't have this problem in conda>26.5. Should we guard against it?

Comment (cbouss) [reply main.py:1610]: Given how other fixes are implemented, with the example right below, this is acceptable.

**Review by cbouss — APPROVED** [review]
LGTM!
